name: Version Increment

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global user.name github-actions
      - run: git config --global user.email github-actions@github.com
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push --follow tags